/**
 * Prisma seed — populates Postgres/Supabase with the same dataset
 * generated by src/lib/data/generators.ts (100 players, mid-season transfers).
 *
 * Run: npm run db:seed
 */
import { PrismaClient } from "@prisma/client";
import {
  generateCompetitions,
  generatePlayers,
  generateTeams,
  generateTeamStatistics,
  PLAYER_COUNT,
} from "../src/lib/data/generators";
import { buildExternalKey } from "../src/etl/transform/transformer";

const prisma = new PrismaClient();

async function main() {
  console.log("Clearing existing data...");
  await prisma.scoutingReport.deleteMany();
  await prisma.playerStatistic.deleteMany();
  await prisma.player.deleteMany();
  await prisma.teamStatistic.deleteMany();
  await prisma.match.deleteMany();
  await prisma.team.deleteMany();
  await prisma.competition.deleteMany();

  console.log("Seeding database...");

  const competitions = generateCompetitions();
  const competitionIdMap = new Map<string, string>();

  for (const c of competitions) {
    const created = await prisma.competition.create({
      data: { name: c.name, country: c.country, tier: c.tier, logoUrl: c.logoUrl },
    });
    competitionIdMap.set(c.id, created.id);
  }

  const teams = generateTeams(competitions);
  const teamIdMap = new Map<string, string>();

  for (const t of teams) {
    const created = await prisma.team.create({
      data: {
        name: t.name,
        shortName: t.shortName,
        country: t.country,
        foundedYear: t.foundedYear,
        stadium: t.stadium,
        competitionId: competitionIdMap.get(t.competitionId)!,
      },
    });
    teamIdMap.set(t.id, created.id);
  }

  const teamStats = generateTeamStatistics(teams);
  for (const stat of teamStats) {
    await prisma.teamStatistic.create({
      data: {
        teamId: teamIdMap.get(stat.teamId)!,
        season: stat.season,
        matchesPlayed: stat.matchesPlayed,
        wins: stat.wins,
        draws: stat.draws,
        losses: stat.losses,
        goalsFor: stat.goalsFor,
        goalsAgainst: stat.goalsAgainst,
        xG: stat.xG,
        xGA: stat.xGA,
        possessionPct: stat.possessionPct,
        passAccuracyPct: stat.passAccuracyPct,
        pressuresPer90: stat.pressuresPer90,
        attackRating: stat.attackRating,
        defenseRating: stat.defenseRating,
      },
    });
  }

  const players = generatePlayers(teams, PLAYER_COUNT);

  for (const p of players) {
    const created = await prisma.player.create({
      data: {
        fullName: p.fullName,
        knownAs: p.knownAs,
        dateOfBirth: new Date(p.dateOfBirth),
        nationality: p.nationality,
        position: p.position,
        secondaryPosition: p.secondaryPosition,
        height: p.height,
        weight: p.weight,
        preferredFoot: p.preferredFoot,
        marketValue: p.marketValue,
        teamId: teamIdMap.get(p.teamId)!,
        strengths: p.strengths,
        weaknesses: p.weaknesses,
      },
    });

    for (const stat of p.history) {
      const teamName = teams.find((t) => t.id === stat.teamId)?.name ?? "unknown";
      await prisma.playerStatistic.create({
        data: {
          externalKey: buildExternalKey(p.fullName, teamName, stat.season),
          playerId: created.id,
          teamId: teamIdMap.get(stat.teamId)!,
          season: stat.season,
          appearances: stat.appearances,
          minutesPlayed: stat.minutesPlayed,
          goals: stat.goals,
          assists: stat.assists,
          xG: stat.xG,
          xA: stat.xA,
          shots: stat.shots,
          shotsOnTarget: stat.shotsOnTarget,
          passes: stat.passes,
          passAccuracy: stat.passAccuracy,
          keyPasses: stat.keyPasses,
          dribblesCompleted: stat.dribblesCompleted,
          tacklesWon: stat.tacklesWon,
          interceptions: stat.interceptions,
          duelsWonPct: stat.duelsWonPct,
          yellowCards: stat.yellowCards,
          redCards: stat.redCards,
          rating: stat.rating,
        },
      });
    }
  }

  console.log(
    `Seed complete: ${competitions.length} competitions, ${teams.length} teams, ${players.length} players.`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
